import pandas as pd
import numpy as np

df=pd.read_csv(r"C:\Users\gakan\OneDrive\Desktop\Xcel Work\_2021-2023 NSS Volunteers Attendance - Sheet1.csv")

column_names = df.columns.tolist()
# print(column_names)
essential_columns = ['S.NO', 'ROLL NUMBER', 'NAME', 'BRANCH']
columns_req =['World Water Day', 'YOGA WEEK ONLINE AND \nOFFLINE', 'FEED THE VOICELESS', 'INTERACTION WITH JUNIORS', 'BLOOD DONATION', 'ANNOUNCEMENT  OF NSS BODY MEMBERS', 'VANAMAHOSTAVAM', 'DISHA APP SENSITIZATION', 'ENERGY SWARAJ', 'AZADI KA\nAMRITMAHOSTAV', 'BEACH CLEANUP DRIVE', 'KAILASGIRI (SWACHH BHARAT EVENT)', 'NSS FOUNDATION\nDAY', 'RAILWAYSTATION CLEANING EVENT', 'COLLEGE SWACHH BHARAT', 'DIWALI EVENT', 'NMMS FORM FILLING EVENT', 'NATIONAL UNITY DAY', 'CANCER AWARNESS', 'DIGNITY  OF\n LABOUR', 'PULAWAMA  \nATTACK\n', 'ROAD SAFETY\n', 'MENSUTRAL\n HYGIENE\n', 'COLLEGE FEST ', 'TUBERCULOSIS \nAWARENESS\n', 'BUTTER MILK \nSUPPLY\n', 'AU CONVECTION\n', 'SEMINAR ON WORLD ENVIRONMENT DAY', 'UBA REGISTRATION VISIT', ' INTERNATIONAL\nYOGA DAY', 'MERI LIFE', 'WEBINAR ON ONE STUDENT ONE TREE', 'ORIENTATION AND AIMS\r\n AND OBJECTIVES OF UBA', 'AWARENESS ON \nDRUG USAGE', '\nMERI DESH MERI MAATI\nPLANTATION EVENT', 'NBA VISIT', 'EK THAREEK\n EK GHANTA EVENT', 'NSS FOUNDATION DAY', 'NSS DAY CAMPAIGN', 'SWACHH SARVEKSHAN \nSURVEY\n', 'WEB DEVELOPMENT', 'POSTER']
l=[]
for col in columns_req:
    r=essential_columns+[col]
    print(r)
    df1=df[r]
    for i in df1.values:
        if i[4]!="Nan":
            print(i[1])
        break